export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PER_PAGE_PRODUCTS = 'FETCH_PER_PAGE_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
export const ADD_ITEMS_TO_WISHLIST = 'ADD_ITEMS_TO_WISHLIST';
export const ADD_WISHLIST_ITEMS_TO_CART = 'ADD_WISHLIST_ITEMS_TO_CART';
export const REMOVE_ITEMS_FROM_CART = 'REMOVE_ITEMS_FROM_CART';
export const REMOVE_ITEMS_FROM_WISHLIST = 'REMOVE_ITEMS_FROM_WISHLIST';
export const UPDATE_PRODUCT_QTY = 'UPDATE_PRODUCT_QTY';
